name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - code-assignment-2
env:
  NODE_JS_VER: 18.x
  SWANKY_NODE_VER: v1.6.0
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: |
        rustup toolchain install nightly-2023-03-05
        rustup default nightly
        rustup show
        rustup component add rust-src

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Install cargo contract
      if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      run: |
        cargo +stable install cargo-dylint dylint-link
        cargo +stable install --force --locked cargo-contract

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_JS_VER }}

    - name: Install swanky-cli
      run: npm install && npm install -g @astar-network/swanky-cli

    - name: Compile contracts
      run: swanky contract compile --all -v

    - name: Download and run substrate-contracts-node
      run: |
          curl -L -o substrate-contracts-node.tar.gz 'https://github.com/paritytech/substrate-contracts-node/releases/download/v0.30.0/substrate-contracts-node-linux.tar.gz' && \
          tar -xf substrate-contracts-node.tar.gz && \
          chmod +x artifacts/substrate-contracts-node-linux/substrate-contracts-node && \
          ./artifacts/substrate-contracts-node-linux/substrate-contracts-node -linfo,runtime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &

    # - name: Download Swanky-node
    #   run: |
    #       sudo wget https://github.com/swankyhub/swanky-node/releases/download/v1.6.0/swanky-node-v1.6.0-ubuntu-x86_64.tar.gz && \
    #       sudo tar -zxvf swanky-node-v1.6.0-ubuntu-x86_64.tar.gz && \
    #       sudo chmod +x swanky-node &

    - name: Test contracts
      run: cargo test
      # run: export CONTRACTS_NODE=$HOME/artifacts/substrate-contracts-node-linux/substrate-contracts-node && cargo test --features e2e-tests
